import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/redux/store";
import RootWrapper from "@/RootWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className=''>
        <RootWrapper>
          {children}
        </RootWrapper>

      </body>
    </html>
  );
}
